### ISSUE TITLE
ValueError exception hit in urls.py 'build_chain' function

### ISSUE THREAD

**Issue by clm0ss** [robinhood-unofficial/pyrh#258]
https://github.com/robinhood-unofficial/pyrh/blob/ff1a0661f01f2b5fa4a30473781ddb72004b3d21/pyrh/urls.py#L175

The trailing slash '/' causes an exception to be encountered in the 'yarl' library.

```
print(rh.get_options('SPY', '2020-06-30', 'call'))
```

>Traceback (most recent call last):
  File "C:/Users/Clayton/PycharmProjects/vix-pc-ratio-algo/algo.py", line 6, in <module>
    print(rh.get_options('SPY', '2020-06-30', 'call'))
  File "C:\Users\Clayton\PycharmProjects\vix-pc-ratio-algo\venv\lib\site-packages\pyrh\robinhood.py", line 498, in get_options
    chain_id = self.get_url(urls.build_chain(instrument_id))["results"][0]["id"]
  File "C:\Users\Clayton\PycharmProjects\vix-pc-ratio-algo\venv\lib\site-packages\pyrh\urls.py", line 175, in build_chain
    OPTIONS_CHAIN_BASE.with_query(equity_instrument_ids=f"{instrument_id}") / "/"
  File "C:\Users\Clayton\PycharmProjects\vix-pc-ratio-algo\venv\lib\site-packages\yarl\__init__.py", line 293, in __truediv__
    raise ValueError(
ValueError: Appending path '/' starting from slash is forbidden

**Comment by clm0ss** [comment]
PR for issue #259
